"""Generator module for producing .env files from schema definitions."""

from __future__ import annotations

import os
from typing import Optional

from envforge.schema import Schema, EnvVar


DEFAULT_PLACEHOLDER = "CHANGE_ME"


def _format_comment(var: EnvVar) -> str:
    """Build a comment block for an EnvVar."""
    lines = []
    if var.description:
        lines.append(f"# {var.description}")
    meta_parts = [f"type={var.type}"]
    if var.required:
        meta_parts.append("required")
    if var.pattern:
        meta_parts.append(f"pattern={var.pattern}")
    if var.allowed_values:
        meta_parts.append("allowed=" + ",".join(str(v) for v in var.allowed_values))
    lines.append("# " + " | ".join(meta_parts))
    return "\n".join(lines)


def generate_env_string(
    schema: Schema,
    environment: Optional[str] = None,
    include_comments: bool = True,
    use_defaults: bool = True,
) -> str:
    """Generate a .env file string from a Schema.

    Args:
        schema: The Schema instance to generate from.
        environment: Optional environment name for contextual header.
        include_comments: Whether to include descriptive comments.
        use_defaults: Whether to fill in default values where available.

    Returns:
        A string representing the .env file content.
    """
    sections: list[str] = []

    header_parts = ["# Generated by envforge"]
    if environment:
        header_parts.append(f"# Environment: {environment}")
    sections.append("\n".join(header_parts))

    for var in schema.variables:
        block: list[str] = []
        if include_comments:
            block.append(_format_comment(var))
        if use_defaults and var.default is not None:
            value = var.default
        elif not var.required:
            value = ""
        else:
            value = DEFAULT_PLACEHOLDER
        block.append(f"{var.name}={value}")
        sections.append("\n".join(block))

    return "\n\n".join(sections) + "\n"


def generate_env_file(
    schema: Schema,
    path: str,
    environment: Optional[str] = None,
    include_comments: bool = True,
    use_defaults: bool = True,
) -> None:
    """Write a generated .env file to disk.

    Args:
        schema: The Schema instance to generate from.
        path: Destination file path.
        environment: Optional environment name.
        include_comments: Whether to include descriptive comments.
        use_defaults: Whether to fill in default values.
    """
    content = generate_env_string(
        schema,
        environment=environment,
        include_comments=include_comments,
        use_defaults=use_defaults,
    )
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
