"""Tests for envforge.generator module."""

from __future__ import annotations

import os
import tempfile

import pytest

from envforge.generator import generate_env_string, generate_env_file, DEFAULT_PLACEHOLDER
from envforge.schema import Schema, EnvVar


@pytest.fixture()
def simple_schema() -> Schema:
    return Schema(
        name="test",
        variables=[
            EnvVar(name="APP_NAME", type="string", default="myapp", description="App name"),
            EnvVar(name="DEBUG", type="boolean", default="false", required=False),
            EnvVar(name="SECRET_KEY", type="string", required=True, description="Secret key"),
            EnvVar(name="PORT", type="integer", required=False),
        ],
    )


class TestGenerateEnvString:
    def test_returns_string(self, simple_schema):
        result = generate_env_string(simple_schema)
        assert isinstance(result, str)

    def test_contains_all_variable_names(self, simple_schema):
        result = generate_env_string(simple_schema)
        for var in simple_schema.variables:
            assert var.name in result

    def test_default_values_used(self, simple_schema):
        result = generate_env_string(simple_schema, use_defaults=True)
        assert "APP_NAME=myapp" in result
        assert "DEBUG=false" in result

    def test_required_without_default_uses_placeholder(self, simple_schema):
        result = generate_env_string(simple_schema, use_defaults=True)
        assert f"SECRET_KEY={DEFAULT_PLACEHOLDER}" in result

    def test_optional_without_default_is_empty(self, simple_schema):
        result = generate_env_string(simple_schema, use_defaults=True)
        assert "PORT=" in result

    def test_comments_included_by_default(self, simple_schema):
        result = generate_env_string(simple_schema)
        assert "# App name" in result
        assert "# Secret key" in result

    def test_comments_excluded_when_disabled(self, simple_schema):
        result = generate_env_string(simple_schema, include_comments=False)
        assert "# App name" not in result
        assert "# Secret key" not in result

    def test_header_present(self, simple_schema):
        result = generate_env_string(simple_schema)
        assert "# Generated by envforge" in result

    def test_environment_in_header(self, simple_schema):
        result = generate_env_string(simple_schema, environment="production")
        assert "# Environment: production" in result

    def test_no_environment_header_when_omitted(self, simple_schema):
        result = generate_env_string(simple_schema)
        assert "# Environment:" not in result

    def test_ends_with_newline(self, simple_schema):
        result = generate_env_string(simple_schema)
        assert result.endswith("\n")

    def test_comment_includes_type(self, simple_schema):
        result = generate_env_string(simple_schema)
        assert "type=string" in result
        assert "type=boolean" in result

    def test_comment_marks_required(self, simple_schema):
        result = generate_env_string(simple_schema)
        assert "required" in result


class TestGenerateEnvFile:
    def test_file_created(self, simple_schema):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = os.path.join(tmpdir, "output.env")
            generate_env_file(simple_schema, path)
            assert os.path.exists(path)

    def test_file_content_matches_string(self, simple_schema):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = os.path.join(tmpdir, "output.env")
            generate_env_file(simple_schema, path, environment="staging")
            expected = generate_env_string(simple_schema, environment="staging")
            with open(path, encoding="utf-8") as fh:
                assert fh.read() == expected

    def test_creates_intermediate_directories(self, simple_schema):
        with tempfile.TemporaryDirectory() as tmpdir:
            path = os.path.join(tmpdir, "nested", "dir", "output.env")
            generate_env_file(simple_schema, path)
            assert os.path.exists(path)
